name: Feature Request
description: Request new features
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please searched for historical issues and check official documentation before opening this issue.
  - type: textarea
    id: what-want
    attributes:
      label: What do you want?
      description: Tell us what do you want?
    validations:
      required: true


